version: '3.7'

services:
  chart-app:
    tty: true
    container_name: chart-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/chart-app'
      - '/chart-app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true